spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Employee Service Route
spring.cloud.gateway.server.webmvc.routes[0].id=employee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/employees/**

# Department Service Route
spring.cloud.gateway.server.webmvc.routes[1].id=department-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/departments/**